#!/bin/sh
# ========================================
# gunicorn - Starts the gunicorn webserver
# ========================================

### BEGIN INIT INFO
# Provides: gunicorn
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts the gunicorn server
# Description: starts gunicorn using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC=gunicorn
DAEMON=/usr/local/bin/gunicorn
NAME=gunicorn
USER=www-data
GROUP=www-data
ROOT=/srv/www/rds
PID_FILE=/var/run/gunicorn/gunicorn.pid
LOG_FILE=/var/log/gunicorn/gunicorn.log
LOG_LEVEL=info
PORT=8000
WORKERS=4
TIMEOUT=3600
SCRIPTNAME=/etc/init.d/$NAME
APP_MODULE='rds.wsgi:application'

[ -x "$DAEMON" ] || exit 0
[ ! -d /var/run/gunicorn ] && mkdir /var/run/gunicorn && chown ${USER}: /var/run/gunicorn
[ ! -d /var/log/gunicorn ] && mkdir /var/log/gunicorn && chown ${USER}: /var/log/gunicorn

start () {
    ARGS="--start --chuid $USER:$GROUP --chdir $ROOT --pidfile $PID_FILE --background --exec $DAEMON"
    DAEMON_ARGS="$APP_MODULE -b 127.0.0.1:$PORT -t $TIMEOUT -p $PID_FILE --log-file $LOG_FILE --log-level $LOG_LEVEL"
    start-stop-daemon $ARGS --test > /dev/null || return 1
    start-stop-daemon $ARGS -- $DAEMON_ARGS || return 2
}

stop () {
    ARGS="--stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID_FILE --name $NAME"
    start-stop-daemon $ARGS
    RETVAL="$?"
    [ "$RETVAL" = 2 ] && return 2
    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
    [ "$?" = 2 ] && return 2
    rm -f $PID_FILE
    return "$RETVAL"
}

case "$1" in
  start)
                echo "Starting $DESC"
                start
                ;;
  stop)
                echo "Stopping $DESC"
                stop
                ;;
  restart)
                echo "Restarting $DESC"
                stop
                sleep 1
                start
                ;;
  *)
                echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
                exit 1
                ;;
esac

exit 0
